src/Feature/PageContent/code/Models/AppCatalogQuickLinks.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PP93Helix.Feature.PageContent.Models
{
    public class AppCatalogQuickLinks
    {
        public List<AppThumb> AppThumbs { get; set; }
        public AppCred AppCred { get; set; } 
        public List<QuickLink> QuickLinks { get; set; }
        public List<QuickLink> BHLinks { get; set; }

    }

    public class AppThumb
    {
        public string ID { get; set; }
        public string AppTitle { get; set; }
        public string AppLaunchURL { get; set; }
        public string AppDesc { get; set; }
        public string AppIcon { get; set; }
    }

    public class AppCred
    {
        [Newtonsoft.Json.JsonProperty("ASP.NET_SessionId")]
        public string SessionId { get; set; }
        public string CsrfToken { get; set; }
        [Newtonsoft.Json.JsonProperty("CtxsAuthId")]
        public string AuthID { get; set; }
        public string NSC_ESNS { get; set; }
    }
    public class QuickLink
    {
        public string ID { get; set; }
        public string ECHOID { get; set; }
        public string LinkTitle { get; set; }
        public string LinkURL { get; set; }
    }

}

src/Feature/PageContent/code/Controllers/AppCatalogQuickLinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Sitecore.Data;
using Sitecore.Data.Fields;
using PP93Helix.Feature.PageContent.Helpers;
using PP93Helix.Feature.PageContent.Models;
using Sitecore.Configuration;
using System.Net;
using System.IO;
using System.Net.Http;
using System.Security.Claims;
using System.Web.Script.Serialization;
using Sitecore;
using Newtonsoft.Json;
using RestSharp;
using Sitecore.Diagnostics;
using HttpCookie = System.Web.HttpCookie;


namespace PP93Helix.Feature.PageContent.Controllers
{
    public class AppCatalogQuickLinksController : Controller
    {
        private readonly string _microserviceBaseAddress = Settings.GetSetting("ppMicroServiceBaseAddress");
        //Quicklinks
        private readonly string _ppMicroserviceGetQLinks = Settings.GetSetting("ppMicroserviceGetQLinks");
        private readonly string _ppMicroserviceSaveQLinks = Settings.GetSetting("ppMicroserviceSaveQLinks");

        //Citrix
        private readonly string _ppMicroserviceGetSfAuth = Settings.GetSetting("ppMicroserviceGetSfAuth");
        private readonly string _ppMicroservicePostAppsList = Settings.GetSetting("ppMicroservicePostAppsList");
        private readonly string _ppMicroservicePostLaunchApp = Settings.GetSetting("ppMicroservicePostLaunchApp");

        private readonly string _icaPath = Settings.GetSetting("icaPath");
        private readonly string _icaPathUrl = Settings.GetSetting("icaPathUrl");

        public ActionResult _appCatalogQuickLinks()
        {
            var appCatQLinks = new Models.AppCatalogQuickLinks();
            var userName = string.Empty;
            if (Context.User.IsAuthenticated)
            {
              Log.Info("Hit Index " + Context.User.Name, Context.User.Name);
              userName = Context.GetUserName();
              Log.Info(string.Concat("User Authenticated - ", userName), Context.User);
              
              var claim = ClaimsPrincipal.Current.Identities.First<ClaimsIdentity>().Claims.FirstOrDefault<Claim>((Claim x) => x.Type == "pwd");
              if (claim != null)
              {
                try
                {
                  var value = claim.Value;
                  var str = string.Concat(Context.GetUserName(), ":", value);
                  Response.Cookies.Clear();
                  Response.Cookies.Add(new HttpCookie("scuser", str));
                }
                catch (Exception e)
                {
                  Log.Error("Exception occurred while saving cookie :: _appCatalogQuickLinks " + e.Message, this);
                }
                 
              }
            }
            else
            {
              return Redirect("~/Login");
            }
            try
            {

              //Citrix Apps
    
              appCatQLinks.AppCred = new AppCred();
              appCatQLinks.AppCred = GetCitrixCreds();
              
              //Get Citrix List
              appCatQLinks.AppThumbs = new List<AppThumb>();
              var sessionId = appCatQLinks.AppCred.SessionId;
              var csrfToken = appCatQLinks.AppCred.CsrfToken;
              var authId = appCatQLinks.AppCred.AuthID;
              appCatQLinks.AppThumbs = GetCitrixApps(sessionId, authId, csrfToken);
             

              //Quicklinks
              appCatQLinks.QuickLinks = new List<QuickLink>();
              var claim = ClaimsPrincipal.Current.Identities.First().Claims.FirstOrDefault(x => x.Type == "echoid");
              
              var echoID = "";
              if (claim!=null)
              {
                echoID = claim.Value;
                Log.Info($"User {userName}'s EchoId is {echoID}", this);
                appCatQLinks.QuickLinks = GetQuickLinks(echoID);
              }
              else
              {
                Log.Info($"User {userName} does not have an echoId, using username for Quick Links.", this);
                if (!string.IsNullOrEmpty(userName))
                  appCatQLinks.QuickLinks = GetQuickLinks(userName);
              }

              appCatQLinks.BHLinks = new List<QuickLink>();

              var linkFolderId = new ID("99CD6607-EB6B-424A-A301-C441DEC79C99");
              var linkFolder = Context.Database.GetItem(linkFolderId);

              var filteredItems =
                RenderingHelper.FilterItemsByTagsMatchingUserRoles(linkFolder.GetChildren().ToArray());
              // we're not going to filter by role anymore. 
              foreach (var link in filteredItems)
              {
                var newLink = new QuickLink();
                LinkField _link = link.Fields["Link"];
                if (_link == null) continue;
                var url = _link.GetFriendlyUrl();
                url = RenderingHelper.parseGeneralLink(_link);
                newLink.LinkURL = url;
                newLink.LinkTitle = _link.Text;
                appCatQLinks.BHLinks.Add(newLink);
                
              }
            }
            catch (Exception ex) {
               Log.Error("PhysicianPortal.Controllers.AppCatalogQuickLinksController Error -> " + ex.ToString(), this);
            }
            return PartialView(appCatQLinks);
        }



       /// <summary>
       /// step 2 get list of apps per user
       /// </summary>
       /// <param name="sessionID"></param>
       /// <param name="AuthID"></param>
       /// <param name="CsrfToken"></param>
       /// <returns></returns>
        public List<AppThumb> GetCitrixApps(string sessionID, string AuthID, string CsrfToken)
        {

            var citrixApps = new List<AppThumb>();
            try
            {
              var json = "{\"SessionId\":\" " + sessionID.Trim() + "\",\"CsrfToken\":\" " + CsrfToken.Trim() +
                            "\",\"AuthID\":\"" + AuthID.Trim() + "\"}".ToString();
                var httpWebResponse = APIHelper.PostDataToMicroService(_ppMicroservicePostAppsList, json);
                if (httpWebResponse != null)
                {
                
                    using (var reader = new StreamReader(httpWebResponse.GetResponseStream()))
                    {
                        var js = new JavaScriptSerializer();
                        var objText = reader.ReadToEnd();
                        citrixApps = js.Deserialize<List<AppThumb>>(objText);
                    }
                }
            }
            catch (Exception)
            {

            }
            return citrixApps;
        }

        /// <summary>
        /// step 1, get citrix creds
        /// </summary>
        /// <returns></returns>
        public AppCred GetCitrixCreds()
        {
            var _appCreds = new AppCred();
            //get scuser auth cookie
            if (Request.Cookies["scuser"] == null) return _appCreds;
            var scuser = Request.Cookies["scuser"].Value;
            try
            {
              //Authenticate User
              var httpWebResponse = APIHelper.GetDataFromMicroService(_ppMicroserviceGetSfAuth, "scuser|" + scuser);
              if (httpWebResponse != null)
              {
                       
                using (var reader = new StreamReader(httpWebResponse.GetResponseStream()))
                {
                  var js = new JavaScriptSerializer();
                  var objText = reader.ReadToEnd();
                  objText = objText.Replace("ASP.NET_SessionId", "SessionId");
                  objText = objText.Replace("CtxsAuthId", "AuthID");
                  _appCreds = js.Deserialize<AppCred>(objText.ToString());
                }
              }
            }
            catch (Exception ex)
            {
              _appCreds = null;
              TempData["QuickLinksResponse"] = "500 Internal Error" + ex.Message;
            }
            return _appCreds;
        }


        public List<QuickLink> GetQuickLinks(string echoID)
        {
            var qlinks = new List<QuickLink>();

            if (!string.IsNullOrEmpty(echoID))
            {
                try
                {
                    var httpWebResponse = APIHelper.GetDataFromMicroService(_ppMicroserviceGetQLinks, "echoid|" + echoID);
                    if (httpWebResponse != null)
                    {
                      
                        using (var reader = new StreamReader(httpWebResponse.GetResponseStream()))
                        {
                            var js = new JavaScriptSerializer();
                            var objText = reader.ReadToEnd();
                            qlinks = js.Deserialize<List<QuickLink>>(objText);
                        }
                    } 
                }
                catch (Exception)
                {
                     qlinks = null;
                    TempData["QuickLinksResponse"] = "500 Internal Error";
                }
            }
            else
            {
                qlinks = null;
                TempData["QuickLinksResponse"] = "No Echo ID";
            }
            return qlinks;
        }

        /// <summary>
        /// version for retrieving ica as part of initial load...
        /// </summary>
        /// <param name=""></param>
        /// <param name="strApiInput"></param>
        /// <param name="title"></param>
        /// <returns></returns>
        public string DownloadICA2(string strApiInput, string title)
        {
            var req = Request.InputStream;
            req.Seek(0, SeekOrigin.Begin);
            
            var request = (HttpWebRequest)WebRequest.Create(_microserviceBaseAddress + _ppMicroservicePostLaunchApp);
            request.ContentType = "Application/Json";
            request.Method = "POST";


            using (var streamWriter = new StreamWriter(request.GetRequestStream()))
            {
                streamWriter.Write(strApiInput);
                streamWriter.Flush();
                streamWriter.Close();
            }
            
            try

src/Feature/PageContent/code/Views/AppCatalogQuickLinks/_appCatalogQuickLinks.cshtml
@using System.Security.Claims
@using Sitecore.Mvc;
@using PP93Helix.Feature.PageContent.Models;
@model AppCatalogQuickLinks
@{
  var claim = ClaimsPrincipal.Current.Identities.First().Claims.FirstOrDefault(x => x.Type == "echoid");
  string echoID = "";
  echoID = claim!=null ? claim.Value : Sitecore.Context.GetUserName();
}
<div id="exTab1">
    <ul class="nav nav-pills marginB-10">
        <li style="" class="active">
            <a href="#one-a" data-toggle="tab">App Catalog</a>
        </li>
        <li style="">
            <a href="#two-a" data-toggle="tab">Quick Links</a>
        </li>
    </ul>
    <div class="mobile-custom">
        <div style="font-size:20px; position:center; padding:6.5%">
            Need the Citrix Receiver on your phone?
        </div>
        <div style="width:50%; height:50%; float:left" >
            <a href='https://itunes.apple.com/us/app/citrix-receiver/id363501921?mt=8&at=10l6Xd'><img alt='Download on the Apple App Store' src='https://linkmaker.itunes.apple.com/assets/shared/badges/en-us/appstore-lrg.svg' style="display:block;overflow:hidden;width:100%;height:auto;background-size:contain;padding:6.45%"/></a>
        </div>
        <div style="width:50%; height:50%; float:left">
            <a href='https://play.google.com/store/apps/details?id=com.citrix.Receiver&hl=en_US&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1'><img alt='Get it on Google Play' src='https://play.google.com/intl/en_us/badges/images/generic/en_badge_web_generic.png' /></a>
        </div>
        <div style="padding-bottom:40px"></div>
    </div>
    <div class="tab-content clearfix">
        
        <div class="tab-pane active" id="one-a">
            <div class="appcenter-flex-div" style="">
                @if (Model.AppThumbs != null)
                {

                    foreach (var item in Model.AppThumbs)
                    {

                        <div class="appcenter-flex-child">
                            <a onclick="gtag('event', 'click', {eventCategory: 'Storefront link', 'event_label': '@item.AppTitle'}); getIcaFile('@Model.AppCred.SessionId', '@Model.AppCred.CsrfToken',  '@Model.AppCred.AuthID', 'https://sf.bmcjax.com/Citrix/PhysiciansWeb/@item.AppLaunchURL', 'https://sf.bmcjax.com/Citrix/PhysiciansWeb/@item.AppLaunchURL', '@item.AppTitle')" href="#"><img src="@item.AppIcon"></a>
                            <a onclick="gtag('event', 'click', {eventCategory: 'Storefront link', 'event_label': '@item.AppTitle'}); getIcaFile('@Model.AppCred.SessionId', '@Model.AppCred.CsrfToken', '@Model.AppCred.AuthID', 'https://sf.bmcjax.com/Citrix/PhysiciansWeb/@item.AppLaunchURL', 'https://sf.bmcjax.com/Citrix/PhysiciansWeb/@item.AppLaunchURL', '@item.AppTitle')" href="#"><p>@item.AppTitle</p></a>
                        </div>
                    }
                }
                else
                {
                    <div>Citrix is currently unavailable. Please contact Baptist Health support.!</div>
                }
            </div><!--END style=display:flex; div-->
        </div>
        <div class="tab-pane" id="two-a">
            <ul class="list-none  padL-5">
                @*@if (!string.IsNullOrWhiteSpace(Sitecore.Context.User.Profile.GetPropertyValue("EchoID").ToString()))*@
                @if (!string.IsNullOrWhiteSpace(echoID))
                {
                  
                    <div class="input_fields_wrap">
                        <div class="qlink-header">My Links</div>
                        @if (Model.QuickLinks != null)
                        {
                            foreach (var item in Model.QuickLinks)
                            {
                              <div class="addlink_dynlist">
                                <li class="addlink-li">
                                  <a class="addlink-a" target="_blank" linkid="@item.ID" echoid="@item.ECHOID" href="@item.LinkURL" onclick="gtag('event', 'click', { eventCategory: 'Quicklinks', 'event_label': '@item.LinkTitle' })">@item.LinkTitle</a>
                                  <span class="show_field" hidden>
                                    <i class="fa fa-times addlink_dynlistX remove_field hand-cursor "></i>|<i class="fa fa-pencil-square-o addlink-edit-icon hand-cursor" aria-hidden="true"></i>
                                  </span>
                                </li>
                              </div>
                            }
                        }

                    </div>
                    <li class="addlink_li">
                        <ul class="list-none addlink_tool padL-0 ">
                            <li>
                                <span class="opensans-bold adlink_text addlink_manage hand-cursor"><i class="fa fa-pencil adlink_fonts" aria-hidden="true"></i><span class="addlink_manage-txt">Manage Links</span></span>
                            </li>
                            <li>
                                <span class="opensans-bold adlink_text hand-cursor addlink-action"><i class="fa fa-plus adlink_fonts" aria-hidden="true"></i>Add Link</span>
                            </li>
                        </ul>
                    </li>
                    <hr style="border-top: 2px solid #eee;" />
                }
                <div class="qlink-header">Helpful Links</div>
                <div>
                    @if (Model.BHLinks != null)
                    {
                        foreach (var item in Model.BHLinks)
                        {
                    <div class="bhlinks">
                        <li><a class="addlink-a" target="blank" href="@item.LinkURL" onclick="gtag('event', 'click', {eventCategory: 'Quicklinks', 'event_label': '@item.LinkTitle'})">@item.LinkTitle</a></li>
                    </div>
                        }
                    }
                </div>
            </ul>
        </div>
    </div>
</div>
<script>
    function postQLinks() {
        var data = JSON.stringify(createQLinkJson());
        //console.log('data to post ', data);

        $.ajax({
            type: "POST",
            url: '@Url.Action("PostQuickLinks", "AppCatalogQuickLinks")',
            data: data,
            contentType: 'application/json',
            success: function (resp) {
                console.log('PostQuickLinks Success');
            },
            error: function (err) {
                console.log('PostQuickLinks Error');
            }
        });
    }

    function createQLinkJson() {
        var linkjson = $(".addlink_dynlist > li a").map(function (index, a) {
            //console.log(a);
            return { ID: a.attributes["linkid"].value, ECHOID: a.attributes["echoid"].value, LinkTitle: a.innerText, LinkURL: a.href };
        }).get();
        
        if (linkjson.length == 0) {
          linkjson = [
            {
              ID: null,
              ECHOID: $('#echoID').text(),
              LinkTitle: null,
              LinkURL: null
            }
          ];
        }

        return linkjson;
    }

    function getIcaFile(SessionId, CsrfToken, AuthID, AppID, AppLaunchURL, AppTitle) {
        var data =  JSON.stringify({
            SessionID: SessionId,
            CsrfToken: CsrfToken,
            AuthId: AuthID,
            AppID: AppID,
            LaunchURL: AppLaunchURL
        });
        console.log(data)
        $.ajax({
            type: "POST",
            url: '@Url.Action("DownloadICA", "AppCatalogQuickLinks")',
            data: data,
            contentType: 'application/json',
            success: function (response, status, request) {
                console.log(response);
                    var a = document.createElement('a');
                    console.log(response);
                    var url = response;
                    a.href = url;
                    document.body.appendChild(a);
                    console.log(AppTitle + ".ica");
                    a.click();
                    setTimeout(function () {
                        document.body.removeChild(a);
                        window.URL.revokeObjectURL(url);
                    }, 1000);
            },
            error: function (err) {
                console.log('Get ICA File Error = ' + err);
            }
        });
    }



</script>